version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app:/src/app
    env_file:
      - .env
  
  redis:
    image: "redis:latest"
    ports:
      - "6389:6389"
    volumes:
      - "./data/redis:/data"
