version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app:/src/app
    env_file:
      - .env
    depends_on:
      - redis
  
  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - "./data/redis:/data"
