version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app:/src/app
    env_file:
      - .env
